# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ata_piix"
    "uhci_hcd"
    "virtio_pci"
    "virtio_blk"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/4e4d0674-26bb-47a2-8097-2e8b52494d24";
    fsType = "btrfs";
    options = [
      "subvol=root"
      "compress=zstd"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/4e4d0674-26bb-47a2-8097-2e8b52494d24";
    fsType = "btrfs";
    options = [
      "subvol=home"
      "compress=zstd"
    ];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/4e4d0674-26bb-47a2-8097-2e8b52494d24";
    fsType = "btrfs";
    options = [
      "subvol=var"
      "compress=zstd"
    ];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/4e4d0674-26bb-47a2-8097-2e8b52494d24";
    fsType = "btrfs";
    options = [ "subvol=swap" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/4e4d0674-26bb-47a2-8097-2e8b52494d24";
    fsType = "btrfs";
    options = [
      "subvol=nix"
      "noatime"
      "compress=zstd"
    ];
  };

  swapDevices = [
    {
      device = "/swap/swapfile";
      size = 4 * 1024;
    }
  ];

  networking.useDHCP = lib.mkDefault true;
  boot.loader.grub.device = "/dev/sda";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
